SET Image=31B7A383-F196-40B5-B932-9BA6D7E4C37A
cd compiler
python ./web-compiler.py "../code/%Image%/%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-00-loss-2.96-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-500-loss-2.08-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-1000-loss-1.05-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-1500-loss-0.62-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-2000-loss-0.42-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-2500-loss-0.29-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-3000-loss-0.30-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-3500-loss-0.13-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-4000-loss-0.18-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-4500-loss-0.19-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-4700-loss-0.22-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-4800-loss-0.18-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-4900-loss-0.21-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-5500-loss-0.13-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-6000-loss-0.17-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-6600-loss-0.13-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-6900-loss-0.10-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-7200-loss-0.14-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-7800-loss-0.12-%Image%.gui"
python ./web-compiler.py "../code/%Image%/batch-8300-loss-0.17-%Image%.gui"

python ./web-compiler.py "../code/%Image%/%Image%.gui" "../code/%Image%/Animation/target.html" 
python ./web-compiler.py "../code/%Image%/batch-00-loss-2.96-%Image%.gui" "../code/%Image%/Animation/1.html" 
python ./web-compiler.py "../code/%Image%/batch-500-loss-2.08-%Image%.gui" "../code/%Image%/Animation/2.html" 
python ./web-compiler.py "../code/%Image%/batch-1000-loss-1.05-%Image%.gui" "../code/%Image%/Animation/3.html" 
python ./web-compiler.py "../code/%Image%/batch-1500-loss-0.62-%Image%.gui" "../code/%Image%/Animation/4.html" 
python ./web-compiler.py "../code/%Image%/batch-2000-loss-0.42-%Image%.gui" "../code/%Image%/Animation/5.html" 
python ./web-compiler.py "../code/%Image%/batch-2500-loss-0.29-%Image%.gui" "../code/%Image%/Animation/6.html" 
python ./web-compiler.py "../code/%Image%/batch-3000-loss-0.30-%Image%.gui" "../code/%Image%/Animation/7.html" 
python ./web-compiler.py "../code/%Image%/batch-3500-loss-0.13-%Image%.gui" "../code/%Image%/Animation/8.html" 
python ./web-compiler.py "../code/%Image%/batch-4000-loss-0.18-%Image%.gui" "../code/%Image%/Animation/9.html" 
python ./web-compiler.py "../code/%Image%/batch-4500-loss-0.19-%Image%.gui" "../code/%Image%/Animation/10.html" 
python ./web-compiler.py "../code/%Image%/batch-4700-loss-0.22-%Image%.gui" "../code/%Image%/Animation/11.html" 
python ./web-compiler.py "../code/%Image%/batch-4800-loss-0.18-%Image%.gui" "../code/%Image%/Animation/12.html" 
python ./web-compiler.py "../code/%Image%/batch-4900-loss-0.21-%Image%.gui" "../code/%Image%/Animation/13.html" 
python ./web-compiler.py "../code/%Image%/batch-5500-loss-0.13-%Image%.gui" "../code/%Image%/Animation/14.html" 
python ./web-compiler.py "../code/%Image%/batch-6000-loss-0.17-%Image%.gui" "../code/%Image%/Animation/15.html" 
python ./web-compiler.py "../code/%Image%/batch-6600-loss-0.13-%Image%.gui" "../code/%Image%/Animation/16.html" 
python ./web-compiler.py "../code/%Image%/batch-6900-loss-0.10-%Image%.gui" "../code/%Image%/Animation/17.html" 
python ./web-compiler.py "../code/%Image%/batch-7200-loss-0.14-%Image%.gui" "../code/%Image%/Animation/18.html" 
python ./web-compiler.py "../code/%Image%/batch-7800-loss-0.12-%Image%.gui" "../code/%Image%/Animation/19.html" 
python ./web-compiler.py "../code/%Image%/batch-8300-loss-0.17-%Image%.gui" "../code/%Image%/Animation/20.html" 
cd ..